# To update nodegroups
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: CapstoneEKS-15iqwZ42Gu0e
  region: us-west-2

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 3
    privateNetworking: false
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: false