apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: 	arn:aws:iam::658886372207:instance-profile/eksctl-capstone-minab-nodegroup-workers-NodeInstanceProfile-1AN6667L8CJVU
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes